export const DEFAULTS = {
  SUGGESTION_INTERVAL_MS: 30_000,
  TRANSCRIPTION_INTERVAL_MS: 30_000,
  SUGGESTION_CONTEXT_CHARS: 4_000,
  EXPANDED_ANSWER_CONTEXT_CHARS: 12_000,
  CHAT_CONTEXT_CHARS: 8_000,
  GROQ_MODEL: 'openai/gpt-oss-120b',
  GROQ_TRANSCRIPTION_MODEL: 'whisper-large-v3',
} as const;
